---
title: "TaskCanceledException on timeout on HttpClient"
date: 2013-01-07T07:46:35Z
tags:
  - C#
  - Lessons learned
  - Multithreading/Parallelism/Asynchronous/Concurrency
category: none
layout: post
---
<p>.NET Framework has a nice new class for all sort of <a href="http://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol">HTTP</a> stuff called <a href="http://msdn.microsoft.com/en-us/library/system.net.http.httpclient.aspx"><code>HttpClient</code></a> (interesting the name wasn't taken before :)). And because it's I/O related it has also bunch on <code>XxxAsync</code> methods to nicely fit into C# 5's <code>async</code>/<code>await</code>.</p>

<p>So you might write code similar to this, based on experience based on previous "network" classes.</p>

<pre class="brush:csharp">
var client = new HttpClient();
client.Timeout = TimeSpan.FromMilliseconds(200); //adjust based on your network
try
{
	var result = await client.GetStringAsync("http://blog.cincura.net/");
}
catch (HttpRequestException)
{
	// handle somehow
	Console.WriteLine("HttpRequestException");
}
catch (TimeoutException)
{
	// handle somehow
	Console.WriteLine("TimeoutException");
}
</pre>

<p>If you try to run it, you'll get unhandled exception, <a href="http://msdn.microsoft.com/en-us/library/system.threading.tasks.taskcanceledexception.aspx"><code>TaskCanceledException</code></a> to be precise. Yep, the timeout is not propagated as <a href="http://msdn.microsoft.com/en-us/library/system.timeoutexception.aspx"><code>TimeoutException</code></a>, but as <code>TaskCanceledException</code>. It caught me off guard a little bit. The documentation for <a href="http://msdn.microsoft.com/en-us/library/system.net.http.httpclient.timeout.aspx"><code>Timeout</code> property</a> touches <a href="http://msdn.microsoft.com/en-us/library/system.threading.cancellationtokensource.aspx"><code>CancellationTokenSource</code></a> and you can feel the steer to <code>TaskCanceledException</code>. But, still, could be mentioned explicitly, will not be that surprising. Or maybe my thinking was skewed.</p>

<p>This code then works correctly.</p>

<pre class="brush:csharp">
var client = new HttpClient();
client.Timeout = TimeSpan.FromMilliseconds(200);
try
{
	var result = await client.GetStringAsync("http://blog.cincura.net/");
}
catch (HttpRequestException)
{
	// handle somehow
	Console.WriteLine("HttpRequestException");
}
//catch (TimeoutException)
//{
//	// handle somehow
//	Console.WriteLine("TimeoutException");
//}
catch (TaskCanceledException)
{
	// handle somehow
	Console.WriteLine("TaskCanceledException");
}
</pre>
